-   id: inspectortiger
    name: inspectortiger
    description: 'Inspects your code'
    entry: inspectortiger
    language: python
    language_version: python3.7
    require_serial: true
    types: [python]
